### ISSUE TITLE
Gentoo does not contain a version of <boost-1.75.0 anymore.

### ISSUE THREAD

**Issue by gerion0** [redneb/gentoo-mapnik-overlay#1]
Currently, the ebuild depends explicitly on <boost-1.75.0 but such a version does not exist anymore in the tree.

**Comment by gerion0** [comment]
The version 3.0.23 is not compatible with boost-1.75 but the new version 3.1.0 compiles fine for me (just renamed the ebuild and removed the boost compability patch). I have not tested the use flags very well.

**Comment by redneb** [comment]
Thanks for the report. I tested 3.1.0 and it seems to be compatible with boost-1.{75,1.76} so I pushed a new ebuild for it.
